## Numpy array and basics
learn about numpy

In [3]:
import numpy as np

## creating array from list

In [6]:
arr_1d=np.array([1,2,3,4,5])
print ("1D array :",arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array :",arr_2d)

1D array : [1 2 3 4 5]
2D array : [[1 2 3]
 [4 5 6]
 [7 8 9]]


## list vs numpy array

In [9]:
py_list=[1,2,3]
print ("python list multiplication :",py_list *2) #make list double with same [1,2,3,1,2,3]

np_array=np.array([1,2,3]) #element wise multiplication
print("python array multiplication: ",np_array*2)

python list multiplication : [1, 2, 3, 1, 2, 3]
python array multiplication:  [2 4 6]


In [17]:
import time

start=time.time()
py_list=[i*2 for i in range(10000000)]
print ("\n List operation time: ",time.time()-start)
# print(py_list)

start=time.time()
np_array=np.arange(10000000)*2
print ("\n Numpy operation time: ",time.time()-start)
# print(np_array)




 List operation time:  1.967919111251831

 Numpy operation time:  0.10184907913208008


## creating array with scratch


In [50]:
import math as m
# creating zeroes array
zeroes=np.zeros((3,4)) #it will create array with 3 row and 4 col of 0
print("zeroes array:\n",zeroes)

#creating ones array
ones=np.ones((3,4))
print("ones array:\n",ones)#it will create array with 3 row and 4 col of 1

full =np.full((2,2),7) #it will create m*n array with constant 
print("Array with constant\n",full)

random=np.random.random((2,2)) #it will crate a random array of m*n we have many class for random

print ("Random array:\n",random)


random_array=np.random.randint(1,100,(3,3)) #print m*n integer in range of 1 to 100
print("print random integer \n",random_array)

# Generate a list of 5 random integers between 10 and 50
random_list = [np.random.randint(10, 50) for _ in range(5)]
print("print random list\n",random_list)

# 3x3 random integer array with values between 1 and 100
random_2d_array = [[int(np.random.random() * 100) + 1 for _ in range(3)] for _ in range(3)]
print("print random 2d array\n",random_2d_array)

sequence=np.arange(0,11,2)# create array in range 0 to 10 with jumping 2
print("sequence array:\n",sequence)

zeroes array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array with constant
 [[7 7]
 [7 7]]
Random array:
 [[0.37489533 0.62960175]
 [0.46685857 0.48892313]]
print random integer 
 [[52 37 68]
 [21 63 38]
 [25 61 84]]
print random list
 [20, 11, 15, 33, 40]
print random 2d array
 [[35, 64, 90], [98, 82, 59], [93, 29, 70]]
sequence array:
 [ 0  2  4  6  8 10]


## vector,matrix and tensor


In [5]:
vector=np.array([1,2,3])
print("vector:\n",vector)

matrix=np.array([[1,2,3],
                 [4,5,6]])
print("Matrix:\n",matrix)

tensor=np.array([[[1,2,3],[4,5,6]],
                 [[7,8,9],[10,11,12]]])

print("Tensor:\n",tensor)

vector:
 [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Array properties

In [8]:
arr=np.array([[1,2,3],
              [4,5,6]])

print("Shape:",arr.shape)
print("Dimension ",arr.ndim)
print("size ",arr.size)
print("DataType ",arr.dtype)

Shape: (2, 3)
Dimension  2
size  6
DataType  int64


## Array Reshaping


In [ ]:
arr=np.arange(12)
print("original array :",arr)

reshaped=arr.reshape((3,4))
print("Reshaped array:\n",reshaped)

#flatten(reutn copy of original array)
flattened=reshaped.flatten()
print("flattened array:\n",flattened)

# ravel (return view ,instead of copy)
raveled=reshaped.ravel()
print("raveled dim array:\n",flattened)

#transpose
#In matrices, the transpose of a matrix is obtained by flipping its rows into columns (or vice versa).
transpose=reshaped.T
print("Transposed Array:\n",transpose)


original array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled dim array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
