## Numpy Array Operation


In [2]:
import numpy as np

In [9]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing ",arr[2:7])
print("With Step ",arr[1:8:2])#every second position
print("Negative indexing ",arr[-3])

Basic Slicing  [3 4 5 6 7]
With Step  [2 4 6 8]
Negative indexing  8


## Slicing on 2d Array


In [5]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print ("Specific element ",arr_2d[1,2])# means 1st row 2nd elemnet
print ("Entire row ",arr_2d[1])#give entire row 1
print ("Entire column ",arr_2d[:,2])# give enire col since [row,col] so [:,1]

Specific element  6
Entire row  [4 5 6]
Entire column  [3 6 9]


## sorting

In [10]:
unsorted=np.array([3,1,4,1,5,8,9,2,4])
print("Sorted Array ",np.sort(unsorted))

arr_2d_unsorted=np.array([[3,2,1],[1,3,2],[2,3,1]])
print("sorted 2d array by column\n",np.sort(arr_2d_unsorted,axis=0))# axis =0 for column
print("sorted 2d array by row\n",np.sort(arr_2d_unsorted,axis=1))# axis =1 for row

Sorted Array  [1 1 2 3 4 4 5 8 9]
sorted 2d array by column
 [[1 2 1]
 [2 3 1]
 [3 3 2]]
sorted 2d array by row
 [[1 2 3]
 [1 2 3]
 [1 2 3]]


## Filters


In [23]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_number=numbers[numbers % 2  ==0]
print("Even numbers :",even_number)



Even numbers : [ 2  4  6  8 10]


## Filter by mask

In [24]:
mask=numbers > 5  # holds whole expression
print("Number greater than 5 ",numbers[mask])

Number greater than 5  [ 6  7  8  9 10]


## fancy indexing vs np.where ()
✅ np.where() creates a new array and does not modify the original array.  
✅ The result will always have the same shape as the original array.  
✅ The syntax is: np.where(condition, value_if_true, value_if_false)  
It works element-wise, applying conditions to each element.  
It’s efficient and commonly used for conditional logic in NumPy arrays.  

In [28]:
index=[0,2,3,5]
print(numbers[index]) # 1 3 4 6 from numbers array


where_result=np.where(numbers > 5) # array ka index store ho jata hai conditon ke anusar 
#print(where_result)#(array([5, 6, 7, 8, 9]),) #index jo 5 se bada ha numbers me
#np.where vi array create karta hai condition ke sath

print ("NP Where ",numbers[where_result])
 

[1 3 4 6]
NP Where  [ 6  7  8  9 10]


In [29]:
condition_array=np.where(numbers >5 ,numbers*4,numbers) #numbers array me jo val 5 se bada hoga usme val*4 ho jaye ga nahi to val
print(condition_array)  #np.where() creates a new array and does not modify the original array.
condition_array=np.where(numbers >5 ,"true","false") #numbers array me jo val 5 se bada hoga usme ture anhi to false 
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


## Adding and removing data

In [31]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

merge=np.concatenate((arr1,arr2))
print ("Merged array : ",merge)

Merged array :  [1 2 3 4 5 6]


### array Compatability

In [34]:
arr1=np.array([1,2,3])
arr2=np.array([3,4,5])
arr3=np.array([1,2,3,6])

print("Compatibilty shapes ",arr1.shape ==arr2.shape)
print("Compatibilty shapes ",arr2.shape ==arr3.shape)

Compatibilty shapes  True
Compatibilty shapes  False


### vstack() and hstack() 
✅ vstack() added one more row to the original array.  

✅ hstack() added one more column to the original array.  


In [ ]:
original=([[1,2],[3,4],[4,5]])
new_row=np.array([[5,6]])

with_new_row=np.vstack((original,new_row))
print("Array with new row \n",with_new_row)

new_col=np.array([[6],[7],[8]])
with_new_col=np.hstack((original ,new_col))
print("Array with new column \n",with_new_col)

Array with new row 
 [[1 2]
 [3 4]
 [4 5]
 [5 6]]
Array with new row 
 [[1 2 6]
 [3 4 7]
 [4 5 8]]


## np.delete()
✅ np.delete() always returns a new array.  
✅ The original array remains unchanged.  
✅ The syntax is:  np.delete(array, index, axis)  



In [ ]:
arr=np.array ([1,2,3,4,5])
delete = np.delete (arr,2)# delete index 2 element and give new array after delete
print ("Array after deletion:",delete)  

arr2D = np.array([[1, 2, 3], 
                  [4, 5, 6]])

# Delete column 1
result = np.delete(arr2D, 1, axis=1) # delete col 

print("delete col 1\n",result)

result2 = np.delete(arr2D, 1, axis=0) # del row

print("delete  row 1\n",result2)


Array after deletion: [1 2 4 5]
delete col 1
 [[1 3]
 [4 6]]
delete  row 1
 [[1 2 3]]
